export const redesMock = [
  {
    id: 1,
    codigo: "P-001",
    foto: "https://picsum.photos/seed/prop1/40",
    direccion: "Calle Falsa 123, Ciudad",
    ciudad: "Ciudad",
    comision: "3%",
    tipoOperacion: "Venta",
    precio: "$250,000",
    inmobiliaria: "Inmobiliaria ABC",
    esPropia: true,
  },
  {
    id: 2,
    codigo: "P-002",
    foto: "https://picsum.photos/seed/prop2/40",
    direccion: "Avenida Principal 456, Pueblo",
    ciudad: "Pueblo",
    comision: "2.5%",
    tipoOperacion: "Venta",
    precio: "$350,000",
    inmobiliaria: "Inmobiliaria XYZ",
    esPropia: false,
  },
  {
    id: 3,
    codigo: "P-003",
    foto: "https://picsum.photos/seed/prop3/40",
    direccion: "Calle Secundaria 789, Villa",
    ciudad: "Villa",
    comision: "4%",
    tipoOperacion: "Alquiler",
    precio: "$1,500/mes",
    inmobiliaria: "Inmobiliaria LMN",
    esPropia: true,
  },
  {
    id: 4,
    codigo: "P-004",
    foto: "https://picsum.photos/seed/prop4/40",
    direccion: "Calle Tranquila 101, Barrio",
    ciudad: "Barrio",
    comision: "3.5%",
    tipoOperacion: "Venta",
    precio: "$200,000",
    inmobiliaria: "Inmobiliaria PQR",
    esPropia: false,
  },
  {
    id: 5,
    codigo: "P-005",
    foto: "https://picsum.photos/seed/prop5/40",
    direccion: "Avenida Exclusiva 202, Zona",
    ciudad: "Zona",
    comision: "5%",
    tipoOperacion: "Venta",
    precio: "$500,000",
    inmobiliaria: "Inmobiliaria UVW",
    esPropia: true,
  },
];